# Generated by Django 3.1.1 on 2020-12-19 11:11

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('not_given', 'not_given'), ('given', 'given')], default='not_given', max_length=20)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_user.account')),
            ],
        ),
    ]
