# Generated by Django 3.1.1 on 2020-12-19 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 19, 15, 5, 40, 869066, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
