# Generated by Django 3.1.1 on 2020-12-21 05:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_staff', '0003_auto_20201221_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryquantity',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=20),
        ),
    ]
