# Generated by Django 3.1.1 on 2020-12-21 10:59

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0001_initial'),
        ('apps_staff', '0004_auto_20201221_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryquantity',
            name='for_who',
            field=models.CharField(choices=[('staff', 'staff'), ('manager', 'manager'), ('technological_man', 'technological_man')], default='staff', max_length=50),
        ),
        migrations.AlterField(
            model_name='staffsalary',
            name='status',
            field=models.CharField(choices=[('not_given', 'not_given'), ('given', 'given'), ('calculated', 'calculated')], default='not_given', max_length=20),
        ),
        migrations.CreateModel(
            name='TechnologicalSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('status', models.CharField(choices=[('not_given', 'not_given'), ('given', 'given'), ('calculated', 'calculated')], default='not_given', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_user.account')),
            ],
        ),
    ]
