# Generated by Django 3.1.1 on 2020-11-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
