# Generated by Django 3.1.1 on 2020-11-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biscuit',
            old_name='biscuit',
            new_name='name',
        ),
    ]
