# Generated by Django 3.1.1 on 2020-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0002_auto_20201122_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='biscuit',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
