# Generated by Django 3.1.1 on 2020-12-04 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0001_initial'),
        ('apps_biscuit', '0003_auto_20201128_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(blank=True, default="so'm", max_length=200, null=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_user.account')),
            ],
        ),
    ]
