# Generated by Django 3.1.1 on 2020-12-04 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0004_producebiscuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='currency',
            field=models.CharField(blank=True, default="so'm", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biscuit',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='UnfitBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recyclable', 'r'), ('unrecyclable', 'unr')], max_length=100)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
    ]
