# Generated by Django 3.1.1 on 2020-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0007_auto_20201210_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebiscuit',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=200, null=True),
        ),
    ]
