# Generated by Django 3.1.1 on 2020-12-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0008_producebiscuit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producebiscuit',
            name='total_price',
        ),
    ]
