# Generated by Django 3.1.1 on 2020-12-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0009_remove_producebiscuit_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biscuit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='biscuit',
            name='price',
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('currency', models.CharField(blank=True, default="so'm", max_length=200, null=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
    ]
