# Generated by Django 3.1.1 on 2020-12-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0013_biscuit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biscuit',
            name='price',
        ),
        migrations.AddField(
            model_name='producebiscuit',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
