# Generated by Django 3.1.1 on 2020-12-12 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0014_auto_20201212_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 12, 14, 10, 34, 592605, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
