# Generated by Django 3.1.1 on 2020-12-13 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0016_producebiscuitlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unfitbiscuit',
            old_name='date',
            new_name='modified_date',
        ),
        migrations.AddField(
            model_name='unfitbiscuit',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 13, 9, 11, 22, 952083, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AddUnFitBiscuitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('recyclable', 'recyclable'), ('unrecyclable', 'unrecyclable')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
        migrations.CreateModel(
            name='AddUnFitBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recyclable', 'recyclable'), ('unrecyclable', 'unrecyclable')], max_length=100)),
                ('total_price', models.PositiveIntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
            ],
        ),
    ]
