# Generated by Django 3.1.1 on 2020-12-13 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_client', '0001_initial'),
        ('apps_biscuit', '0018_auto_20201213_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingBiscuitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default="so'm", max_length=200)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('credit_card', 'credit_card'), ('debt', 'debt')], default='cash', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_client.client')),
            ],
        ),
        migrations.CreateModel(
            name='BuyingBiscuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default="so'm", max_length=200)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('credit_card', 'credit_card'), ('debt', 'debt')], default='cash', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_client.client')),
            ],
        ),
    ]
