# Generated by Django 3.1.1 on 2020-12-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0019_buyingbiscuit_buyingbiscuitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingbiscuitlog',
            name='sale_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
