# Generated by Django 3.1.1 on 2020-12-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0020_buyingbiscuitlog_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingbiscuit',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('take_driver', 'take_driver'), ('delivered', 'delivered')], default='pending', max_length=50),
        ),
    ]
