# Generated by Django 3.1.1 on 2020-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0022_auto_20201213_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuit',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
