# Generated by Django 3.1.1 on 2020-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0024_auto_20201213_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producebiscuit',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
