# Generated by Django 3.1.1 on 2020-12-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0028_producebiscuit_for_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producebiscuitlog',
            name='total_price',
        ),
    ]
