# Generated by Django 3.1.1 on 2020-12-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0029_remove_producebiscuitlog_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producebiscuit',
            name='total_price',
        ),
    ]
