# Generated by Django 3.1.1 on 2020-12-14 17:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0030_remove_producebiscuit_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBiscuitPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
