# Generated by Django 3.1.1 on 2020-12-15 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0032_incomebiscuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebiscuitprice',
            name='biscuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit'),
        ),
    ]
