# Generated by Django 3.1.1 on 2020-12-19 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0033_auto_20201215_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
