# Generated by Django 3.1.1 on 2021-01-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0034_biscuit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producebiscuit',
            name='staff',
        ),
    ]
