# Generated by Django 3.1.1 on 2021-02-08 04:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_biscuit', '0036_returnbiscuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyingbiscuit',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
