# Generated by Django 3.1.1 on 2020-11-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0002_addproduct_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_product.supplier'),
        ),
    ]
