# Generated by Django 3.1.1 on 2020-11-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0001_initial'),
        ('apps_product', '0004_auto_20201121_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='warehouseman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_user.account'),
        ),
    ]
