# Generated by Django 3.1.1 on 2020-11-21 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0005_auto_20201121_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addproduct',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
