# Generated by Django 3.1.1 on 2020-11-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_supplier', '0001_initial'),
        ('apps_product', '0006_auto_20201121_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_supplier.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
