# Generated by Django 3.1.1 on 2020-11-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0008_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, default='kg', max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
