# Generated by Django 3.1.1 on 2020-11-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0010_addmanufacturedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmanufacturedproduct',
            name='currency',
        ),
    ]
