# Generated by Django 3.1.1 on 2020-12-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0011_remove_addmanufacturedproduct_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProductLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_product_id', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.manufacturedproduct')),
            ],
        ),
    ]
