# Generated by Django 3.1.1 on 2020-12-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0017_remove_addmanufacturedproduct_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmanufacturedproduct',
            name='warehouseman',
        ),
        migrations.CreateModel(
            name='ManufacturedProductPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('currency', models.CharField(blank=True, default="so'm", max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.manufacturedproduct')),
            ],
        ),
        migrations.CreateModel(
            name='AddManufacturedProductLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactured_product_id', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.manufacturedproduct')),
            ],
        ),
    ]
