# Generated by Django 3.1.1 on 2020-12-14 10:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0021_auto_20201214_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='currency',
            field=models.CharField(choices=[('SOM', 1), ('USD', 2)], max_length=20),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=20),
        ),
    ]
