# Generated by Django 3.1.1 on 2020-12-14 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0023_auto_20201214_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmanufacturedproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addmanufacturedproductlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproductlog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproductlog',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='addproductlog',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='manufacturedproductpricelist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='productpricelist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
