# Generated by Django 3.1.1 on 2020-12-19 15:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0025_addmanufacturedproduct_for_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturedproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
