# Generated by Django 3.1.1 on 2020-12-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0027_subproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='warehouseman',
        ),
        migrations.AddField(
            model_name='subproduct',
            name='log_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
