# Generated by Django 3.1.1 on 2020-12-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0028_auto_20201225_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='currency',
            field=models.CharField(choices=[('SOM', 1), ('USD', 2)], default='SOM', max_length=20),
        ),
    ]
