# Generated by Django 3.1.1 on 2020-12-25 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0030_auto_20201225_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20),
        ),
    ]
