# Generated by Django 3.1.1 on 2020-11-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_product', '0002_addproduct_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('usable ', 1), ('unusable ', 2)], max_length=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.product')),
            ],
        ),
    ]
