# Generated by Django 3.1.1 on 2020-11-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='status',
        ),
    ]
