# Generated by Django 3.1.1 on 2020-11-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_warehouse', '0002_remove_warehouseproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='unit_of_measurement',
            field=models.CharField(blank=True, default='kg', max_length=200, null=True),
        ),
    ]
