# Generated by Django 3.1.1 on 2020-11-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_warehouse', '0003_warehouseproduct_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='average_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
