# Generated by Django 3.1.1 on 2020-11-25 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_product', '0009_manufacturedproduct'),
        ('apps_warehouse', '0006_warehousebiscuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouseManufacturedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('average_price', models.PositiveIntegerField(default=0)),
                ('unit_of_measurement', models.CharField(blank=True, default='kg', max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('manufactured_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_product.manufacturedproduct')),
            ],
        ),
    ]
