# Generated by Django 3.1.1 on 2020-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_warehouse', '0008_warehouseunfitbiscuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseunfitbiscuit',
            name='status',
            field=models.CharField(blank=True, choices=[('recyclable', 'recyclable'), ('unrecyclable', 'unrecyclable')], max_length=100, null=True),
        ),
    ]
