# Generated by Django 3.1.1 on 2020-12-14 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_warehouse', '0011_auto_20201214_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousebiscuit',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehousebiscuit',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehousebiscuit',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehousemanufacturedproduct',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehousemanufacturedproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehousemanufacturedproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
