# Generated by Django 3.1.1 on 2020-11-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_biscuit', '0002_auto_20201122_1105'),
        ('apps_product', '0007_auto_20201122_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiscuitRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit_of_measurement', models.CharField(blank=True, default='kg', max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('biscuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_biscuit.biscuit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps_product.product')),
            ],
        ),
    ]
