# Generated by Django 3.1.1 on 2020-12-14 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_recipe', '0003_auto_20201214_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuitrecipe',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='manufacturedproductrecipe',
            name='value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
