# Generated by Django 3.1.1 on 2021-01-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=50, null=True),
        ),
    ]
