# Generated by Django 3.1.1 on 2021-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_order', '0002_auto_20210129_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
