# Generated by Django 3.1.1 on 2020-11-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='inn',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='m_f_o',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='x_p',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
