# Generated by Django 3.1.1 on 2020-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_expense', '0003_quantityexpense_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityexpense',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('completed', 'completed')], default='new', max_length=30),
        ),
    ]
