# Generated by Django 3.1.1 on 2020-12-14 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_expense', '0004_quantityexpense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantityexpense',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10),
        ),
    ]
